// Code generated by bencgen golang. DO NOT EDIT.
// source: ../schemas/uint.benc

package unsignedInt

import (
    "github.com/deneonet/benc/std"
    "github.com/deneonet/benc/impl/gen"
)

// Struct - UintTest
type UintTest struct {
    Ui64 uint64
    Ui64Arr []uint64
    Ui64Map map[uint64]uint32
    Ui32 uint32
    Ui16 uint16
    Ui uint
}

// Reserved Ids - UintTest
var uintTestRIds = []uint16{}

// Size - UintTest
func (uintTest *UintTest) Size() int {
    return uintTest.size(0)
}

// Nested Size - UintTest
func (uintTest *UintTest) size(id uint16) (s int) {
    s += bstd.SizeUint64() + 2
    s += bstd.SizeSlice(uintTest.Ui64Arr, bstd.SizeUint64) + 2
    s += bstd.SizeMap(uintTest.Ui64Map, bstd.SizeUint64, bstd.SizeUint32) + 2
    s += bstd.SizeUint32() + 2
    s += bstd.SizeUint16() + 2
    s += bstd.SizeUint(uintTest.Ui) + 2

    if id > 255 {
        s += 5
        return
    }
    s += 4
    return
}

// SizePlain - UintTest
func (uintTest *UintTest) SizePlain() (s int) {
    s += bstd.SizeUint64()
    s += bstd.SizeSlice(uintTest.Ui64Arr, bstd.SizeUint64)
    s += bstd.SizeMap(uintTest.Ui64Map, bstd.SizeUint64, bstd.SizeUint32)
    s += bstd.SizeUint32()
    s += bstd.SizeUint16()
    s += bstd.SizeUint(uintTest.Ui)
    return
}

// Marshal - UintTest
func (uintTest *UintTest) Marshal(b []byte) {
    uintTest.marshal(0, b, 0)
}

// Nested Marshal - UintTest
func (uintTest *UintTest) marshal(tn int, b []byte, id uint16) (n int) {
    n = bgenimpl.MarshalTag(tn, b, bgenimpl.Container, id)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Fixed64, 1)
    n = bstd.MarshalUint64(n, b, uintTest.Ui64)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.ArrayMap, 2)
    n = bstd.MarshalSlice(n, b, uintTest.Ui64Arr, bstd.MarshalUint64)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.ArrayMap, 3)
    n = bstd.MarshalMap(n, b, uintTest.Ui64Map, bstd.MarshalUint64, bstd.MarshalUint32)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Fixed32, 4)
    n = bstd.MarshalUint32(n, b, uintTest.Ui32)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Fixed16, 5)
    n = bstd.MarshalUint16(n, b, uintTest.Ui16)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Varint, 7)
    n = bstd.MarshalUint(n, b, uintTest.Ui)

    n += 2
    b[n-2] = 1
    b[n-1] = 1
    return
}

// MarshalPlain - UintTest
func (uintTest *UintTest) MarshalPlain(tn int, b []byte) (n int) {
    n = tn
    n = bstd.MarshalUint64(n, b, uintTest.Ui64)
    n = bstd.MarshalSlice(n, b, uintTest.Ui64Arr, bstd.MarshalUint64)
    n = bstd.MarshalMap(n, b, uintTest.Ui64Map, bstd.MarshalUint64, bstd.MarshalUint32)
    n = bstd.MarshalUint32(n, b, uintTest.Ui32)
    n = bstd.MarshalUint16(n, b, uintTest.Ui16)
    n = bstd.MarshalUint(n, b, uintTest.Ui)
    return n
}

// Unmarshal - UintTest
func (uintTest *UintTest) Unmarshal(b []byte) (err error) {
    _, err = uintTest.unmarshal(0, b, []uint16{}, 0)
    return
}

// Nested Unmarshal - UintTest
func (uintTest *UintTest) unmarshal(tn int, b []byte, r []uint16, id uint16) (n int, err error) {
    var ok bool
    if n, ok, err = bgenimpl.HandleCompatibility(tn, b, r, id); !ok {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, uintTestRIds, 1); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, uintTest.Ui64, err = bstd.UnmarshalUint64(n, b); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, uintTestRIds, 2); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, uintTest.Ui64Arr, err = bstd.UnmarshalSlice[uint64](n, b, bstd.UnmarshalUint64); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, uintTestRIds, 3); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, uintTest.Ui64Map, err = bstd.UnmarshalMap[uint64, uint32](n, b, bstd.UnmarshalUint64, bstd.UnmarshalUint32); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, uintTestRIds, 4); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, uintTest.Ui32, err = bstd.UnmarshalUint32(n, b); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, uintTestRIds, 5); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, uintTest.Ui16, err = bstd.UnmarshalUint16(n, b); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, uintTestRIds, 7); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, uintTest.Ui, err = bstd.UnmarshalUint(n, b); err != nil {
            return
        }
    }
    n += 2
    return
}

// UnmarshalPlain - UintTest
func (uintTest *UintTest) UnmarshalPlain(tn int, b []byte) (n int, err error) {
    n = tn
    if n, uintTest.Ui64, err = bstd.UnmarshalUint64(n, b); err != nil {
        return
    }
    if n, uintTest.Ui64Arr, err = bstd.UnmarshalSlice[uint64](n, b, bstd.UnmarshalUint64); err != nil {
        return
    }
    if n, uintTest.Ui64Map, err = bstd.UnmarshalMap[uint64, uint32](n, b, bstd.UnmarshalUint64, bstd.UnmarshalUint32); err != nil {
        return
    }
    if n, uintTest.Ui32, err = bstd.UnmarshalUint32(n, b); err != nil {
        return
    }
    if n, uintTest.Ui16, err = bstd.UnmarshalUint16(n, b); err != nil {
        return
    }
    if n, uintTest.Ui, err = bstd.UnmarshalUint(n, b); err != nil {
        return
    }
    return
}

